### PR TITLE
UPGRADE Silverstripe 4 compatibility

### PR DESCRIPTION
**Pull request by muskie9**
I've gone through and updated the general items required to run on Silverstripe 4. I haven't tested yet but hope to in the coming week. I took a shot at updating the readme as well, however I really just replaced some references for active directory with the SAML module and updated code examples to have FQN's.

If anything jumps out that needs adjusting let me know and I can update, otherwise we'll see what happens in testing.

### CODE REVIEW

**Comment by madmatt** [comment]
Thanks Nic, this looks great! How have you gotten on with testing this against Silverstripe 4? If it's working well, let's get this merged in :)

**Comment by muskie9** [comment]
Working through one issue but it's most likely unrelated to this upgrade. Once confirmed I'll merge!

**Comment by muskie9** [comment]
@madmatt it's been a long time coming, but barring any last minute issues that pop up in testing, I think this is probably set if you don't see any needed revisions.

**Comment by madmatt** [comment]
Hey @muskie9, amazing thank you!

I have just one request - could you please change the namespace to be `Madmatt` instead of `MadMatt`? Super minor, hopefully just a find & replace! Once done, I'm happy for you to merge this. Thanks so much for your help!

**Comment by muskie9** [comment]
@madmatt I'm a bit behind on this but I've updated the namespace. Just doing a final test quick to be sure I didn't miss anything.

**Comment by muskie9** [comment]
Everything seems to work on my end. Let me know if there's any other feedback!

**Comment by madmatt** [comment]
Thanks @muskie9, looks good! I'll merge it in now and release a new major version!

**Pull request merged**
